### ISSUE TITLE
Better option

### ISSUE THREAD

**Issue by rahulkapoor90** [csivit/members-app-chatbot#2]
chatbot developer and vit student here. There is a much better option for your use case which is chatfuel. easy to deliver and build.

**Comment by pradyunsg** [comment]
Hey @rahulkapoor90!

Thanks for bringing chatfuel.com to our notice! We are considering the use of other online services (wit.ai, api.ai and more) for powering the chatbot as well.

I'll close this issue for now since this has been added to our internal list of possible services.
